%YAML:1.0

# This is a config file used for the D435 and D435i camera.
# Used to run VINS Fusion for deployment during ST_Deepak

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/imu"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"
output_path: "/home/EstimationUser/estimation_ws/src/VINS-Fusion/vins_estimator/output/"

cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 480
   
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.00325957,  0.00838682,  0.99995952, -0.00009049,  # -0.00006122
          -0.99996363,  -0.00785404, 0.00332545,   0.00022833,     # 0.00016393
           0.00788161,  -0.99993399, 0.00836091,  -0.00018769,   # -0.00014977
           0., 0., 0., 1. ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.00486907,  0.00790827,   0.99995687, 0.00018211,    # 0.00014213
           -0.99995754,  -0.00778463,  0.00493064, -0.04987735,   # -0.04994188
           0.00782329,  -0.99993843,  0.00787003, 0.00007389,    # 0.00014571
           0., 0., 0., 1. ]

#Multiple thread support
multiple_thread: 1

#feature tracker parameters
max_cnt: 150             # max feature number in feature tracking
min_dist: 10            # min distance between two features 
freq: 0                # frequency (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequency will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.01  # max solver iteration time (ms), to guarantee real time
max_num_iterations: 6   # max solver iterations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.5          # accelerometer measurement noise standard deviation. #0.2   0.04
acc_n_z: 2.0
gyr_n: 0.05         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.0004         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 0.0002       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.00               # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/EstimationUser/estimation_ws/src/VINS-Fusion/vins_estimator/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization purpose; you can close this function by setting 0 
